name: movie_master_detail
description: Flutter recruitment task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  json_annotation: 4.9.0
  http: 1.3.0
  shared_preferences: 2.2.2
  rxdart: 0.28.0
  collection: 1.19.1
  flutter_bloc: 9.1.1
  equatable: 2.0.7
  intl_utils: 2.8.10
  copy_with_extension: 6.0.1
  clock: 1.1.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.15
  json_serializable: 6.9.5
  mocktail: 1.0.4
  bloc_test: 10.0.0
  copy_with_extension_gen: 6.0.1
  fake_async: 1.3.2

flutter:
  uses-material-design: true
  generate: true